[package]
name = "flowforge"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
	"crates/api", "crates/app", "crates/domain",
]

[dependencies]
api = { path = "crates/api" }
app = { path = "crates/app" }
domain = { path = "crates/domain" }

anyhow = "1.0.102"
axum = "0.8.8"
chrono = "0.4.44"
serde = "1.0.228"
tokio = { version = "1", features = ["full"] }

